FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Önce sadece sln ve csproj dosyaları kopyalanır
COPY *.sln .
COPY TezGel.Application/*.csproj TezGel.Application/
COPY TezGel.Domain/*.csproj TezGel.Domain/
COPY TezGel.Infrastructure/*.csproj TezGel.Infrastructure/
COPY TezGel.Persistence/*.csproj TezGel.Persistence/
COPY TezGel.API/*.csproj TezGel.API/
COPY TezGel.ReservationConsumer/*.csproj TezGel.ReservationConsumer/

# dotnet restore (csproj dosyaları üzerinden)
RUN dotnet restore

# 🔁 Şimdi tüm dosyalar kopyalanır (klasörleriyle birlikte)
COPY . .

WORKDIR /src/TezGel.ReservationConsumer
RUN dotnet publish -c Release -o /app/publish

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TezGel.ReservationConsumer.dll"]
